/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kethua;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AD
 */
public class Qlydiemthiview extends javax.swing.JFrame {
    List<SVgrademodel>s = new ArrayList<>();
    DefaultTableModel tbmodel ;
    public Qlydiemthiview() {
        initComponents();
        tbmodel = (DefaultTableModel)jTable1.getModel();
        inittable();
        filltable();
    }
    private void inittable(){
        String[] columns = new String[] {"Mã sinh viên","Tên sinh viên", "điểm giữa kỳ", "điểm cuối kỳ", "tổng điểm","tên môn học",""};
        tbmodel.setColumnIdentifiers(columns);
    }
      private void filltable(){
       tbmodel.setRowCount(0);
       GradeController manager = new GradeController();
       s = manager.getall();
       for(SVgrademodel grade: s){
           tbmodel.addRow(new Object[]{grade.getId(),grade.getTensv(), grade.getDiemgk(), grade.getDiemck(),grade.getDiemtong(),
                                        grade.getSubject()});
       }
    }
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        SVnametxt = new javax.swing.JTextField();
        gkytxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ckytxt = new javax.swing.JTextField();
        monhoctxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ADDbtn = new javax.swing.JButton();
        DELbtn = new javax.swing.JButton();
        Truotbtn = new javax.swing.JButton();
        hocbongbtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        IDtxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Tên sinh viên");

        jLabel2.setText("điểm giữa kỳ");

        jLabel3.setText("điểm cuối kỳ");

        jLabel4.setText("môn học");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        ADDbtn.setIcon(new javax.swing.ImageIcon("G:\\daucong.png")); // NOI18N
        ADDbtn.setText("Thêm");
        ADDbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDbtnActionPerformed(evt);
            }
        });

        DELbtn.setIcon(new javax.swing.ImageIcon("G:\\ảnh thùng rác.png")); // NOI18N
        DELbtn.setText("Xóa");
        DELbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELbtnActionPerformed(evt);
            }
        });

        Truotbtn.setIcon(new javax.swing.ImageIcon("G:\\ảnh trượt môn.png")); // NOI18N
        Truotbtn.setText("DS truot mon");
        Truotbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TruotbtnActionPerformed(evt);
            }
        });

        hocbongbtn.setIcon(new javax.swing.ImageIcon("G:\\ảnh học bổng.png")); // NOI18N
        hocbongbtn.setText("DS hoc bong");
        hocbongbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hocbongbtnActionPerformed(evt);
            }
        });

        jLabel5.setText("ID sinh viên");

        IDtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDtxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 807, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(73, 73, 73)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(gkytxt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SVnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(253, 253, 253)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ADDbtn)
                                        .addGap(92, 92, 92)
                                        .addComponent(DELbtn)))
                                .addGap(38, 38, 38)
                                .addComponent(IDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Truotbtn)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(monhoctxt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ckytxt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hocbongbtn)
                                .addGap(10, 10, 10)))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(SVnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(ckytxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(IDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gkytxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(monhoctxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ADDbtn)
                    .addComponent(DELbtn)
                    .addComponent(Truotbtn)
                    .addComponent(hocbongbtn))
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ADDbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDbtnActionPerformed
        int id = Integer.parseInt(IDtxt.getText());
        String tensv = SVnametxt.getText();
        float diemGK = Float.parseFloat(gkytxt.getText());
        float diemCK = Float.parseFloat(ckytxt.getText());
        String monhoc = monhoctxt.getText();
        SVgrademodel sinhvien = new SVgrademodel(id, tensv, diemGK, diemCK, monhoc);
        GradeController.insert(sinhvien);
        filltable();
    }//GEN-LAST:event_ADDbtnActionPerformed

    private void DELbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELbtnActionPerformed
        int selected = jTable1.getSelectedRow();
      if(selected >= 0){
          SVgrademodel grade = s.get(selected);
          int option = JOptionPane.showConfirmDialog(this, "Do you want to delete this item?");
          System.out.println("option : " + option);
          if(option == 0){
              GradeController.delete(grade.getId(),grade.getSubject());
              filltable();
          }
      }
    }//GEN-LAST:event_DELbtnActionPerformed

    private void TruotbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TruotbtnActionPerformed
        filltable1();
    }//GEN-LAST:event_TruotbtnActionPerformed

    private void IDtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDtxtActionPerformed

    private void hocbongbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hocbongbtnActionPerformed
        filltable2();
    }//GEN-LAST:event_hocbongbtnActionPerformed
   private void filltable1(){
       tbmodel.setRowCount(0);
       GradeController manager = new GradeController();
       s = manager.HStruot();
       for(SVgrademodel grade: s){
           tbmodel.addRow(new Object[]{grade.getId(),grade.getTensv(),grade.getSubject(), grade.getTruot()});
       }
   }
    private void filltable2(){
       tbmodel.setRowCount(0);
       GradeController manager = new GradeController();
       s = manager.hocbong1();
       for(SVgrademodel grade: s){
           tbmodel.addRow(new Object[]{grade.getId(),grade.getTensv(), grade.getDiemTB(),grade.getDiemchu()});
       }
   }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Qlydiemthiview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Qlydiemthiview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Qlydiemthiview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Qlydiemthiview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Qlydiemthiview().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADDbtn;
    private javax.swing.JButton DELbtn;
    private javax.swing.JTextField IDtxt;
    private javax.swing.JTextField SVnametxt;
    private javax.swing.JButton Truotbtn;
    private javax.swing.JTextField ckytxt;
    private javax.swing.JTextField gkytxt;
    private javax.swing.JButton hocbongbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField monhoctxt;
    // End of variables declaration//GEN-END:variables
}
