/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kethua;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author AD
 */
public class QlySInhvien extends javax.swing.JFrame {

     List<Sinhvien>s = new ArrayList<>();
    DefaultTableModel tbmodel ;
    public QlySInhvien() {
        initComponents();
        tbmodel = (DefaultTableModel)jTable1.getModel();
         inittable();
        filltable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        MASVtxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        HOTENtxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        EMAILtxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        GENDERtxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        PHONENUMtxt = new javax.swing.JTextField();
        ADDbtn = new javax.swing.JButton();
        DELbtn = new javax.swing.JButton();
        FINDbtn = new javax.swing.JButton();
        UpdateBTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Mã sinh viên");

        MASVtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MASVtxtActionPerformed(evt);
            }
        });

        jLabel2.setText("Họ tên sinh viên");

        jLabel3.setText("Email");

        jLabel4.setText("Giới tính");

        jLabel5.setText("Số điện thoại");

        ADDbtn.setIcon(new javax.swing.ImageIcon("G:\\daucong.png")); // NOI18N
        ADDbtn.setText("Thêm");
        ADDbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDbtnActionPerformed(evt);
            }
        });

        DELbtn.setIcon(new javax.swing.ImageIcon("G:\\ảnh thùng rác.png")); // NOI18N
        DELbtn.setText("Xóa");
        DELbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELbtnActionPerformed(evt);
            }
        });

        FINDbtn.setIcon(new javax.swing.ImageIcon("G:\\kinhlup.png")); // NOI18N
        FINDbtn.setText("Tìm");
        FINDbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FINDbtnActionPerformed(evt);
            }
        });

        UpdateBTN.setIcon(new javax.swing.ImageIcon("G:\\ảnh reload.png")); // NOI18N
        UpdateBTN.setText("Cập nhật");
        UpdateBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBTNActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EMAILtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(MASVtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(HOTENtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(72, 72, 72)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(41, 41, 41)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(PHONENUMtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(GENDERtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(ADDbtn)
                        .addGap(53, 53, 53)
                        .addComponent(DELbtn)
                        .addGap(51, 51, 51)
                        .addComponent(FINDbtn)
                        .addGap(50, 50, 50)
                        .addComponent(UpdateBTN)))
                .addContainerGap(29, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(MASVtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(GENDERtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(HOTENtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PHONENUMtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(EMAILtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ADDbtn)
                    .addComponent(DELbtn)
                    .addComponent(FINDbtn)
                    .addComponent(UpdateBTN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MASVtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MASVtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MASVtxtActionPerformed

    private void ADDbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDbtnActionPerformed
        int masv = Integer.parseInt(MASVtxt.getText());
        String name = HOTENtxt.getText();
        String gender = GENDERtxt.getText();
        String Email = EMAILtxt.getText();
        String Phone = PHONENUMtxt.getText();
        Sinhvien student = new Sinhvien(masv, name, Email, Phone, gender);
        StudentManager manage = new StudentManager();
        manage.insert(student);
        filltable();
    }//GEN-LAST:event_ADDbtnActionPerformed
    
    private void DELbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELbtnActionPerformed
      int selected = jTable1.getSelectedRow();
      if(selected >= 0){
          Sinhvien student = s.get(selected);
          int option = JOptionPane.showConfirmDialog(this, "Do you want to delete this item?");
          System.out.println("option : " + option);
          if(option == 0){
              StudentManager.delete(student.getMasv());
              filltable();
          }
      }
    }//GEN-LAST:event_DELbtnActionPerformed

    private void UpdateBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBTNActionPerformed
        int masv = Integer.parseInt(MASVtxt.getText());
        String name = HOTENtxt.getText();
        String gender = GENDERtxt.getText();
        String Email = EMAILtxt.getText();
        String Phone = PHONENUMtxt.getText();
        Sinhvien student = new Sinhvien(masv, name, Email, Phone, gender);
        StudentManager manage = new StudentManager();
        manage.update(student);
        filltable();
    }//GEN-LAST:event_UpdateBTNActionPerformed

    private void FINDbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FINDbtnActionPerformed
        int ID = Integer.parseInt(MASVtxt.getText());
        StudentManager manage = new StudentManager();
        s = manage.FindbyId(ID);
        tbmodel.setRowCount(0);
        for(Sinhvien sinhvien: s){
           tbmodel.addRow(new Object[]{sinhvien.getMasv(), sinhvien.getTensv(),sinhvien.getGender(),
                                       sinhvien.getEmail(), sinhvien.getPhonenum()});
       }
      
    }//GEN-LAST:event_FINDbtnActionPerformed
    private void filltable(){
       tbmodel.setRowCount(0);
       StudentManager manage = new StudentManager();
       s = manage.getall();
       for(Sinhvien sinhvien: s){
           tbmodel.addRow(new Object[]{sinhvien.getMasv(), sinhvien.getTensv(),sinhvien.getGender(),
                                       sinhvien.getEmail(), sinhvien.getPhonenum()});
       }
      
    }
    private void inittable(){
        String[] columns = new String[] {"Mã sinh viên", "tên sinh viên", "giới tính", "email","sdt"};
        tbmodel.setColumnIdentifiers(columns);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QlySInhvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QlySInhvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QlySInhvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QlySInhvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QlySInhvien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADDbtn;
    private javax.swing.JButton DELbtn;
    private javax.swing.JTextField EMAILtxt;
    private javax.swing.JButton FINDbtn;
    private javax.swing.JTextField GENDERtxt;
    private javax.swing.JTextField HOTENtxt;
    private javax.swing.JTextField MASVtxt;
    private javax.swing.JTextField PHONENUMtxt;
    private javax.swing.JButton UpdateBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
